stateDiagram-v2
    state Global {
        state Method {
            state Local {
                int
                boolean
            }
            
        }
    	int[]
    	boolean[]
    }


